#!/bin/bash

# **************************************************************************
# OMI SO2 File Copy Script: 
#
#  This script is run on a crontab job and copies files generated by the 
# OMI processing to various locations:
#
#  *The latest data files are copied to the Volcano web server for
#   display on the monitoring pages.
#
#  *Files for the Vanuatu region for the last 5 days are uploaded to the
#   public FTP site. 
#
# **************************************************************************


# Find command with -execdir option (used below) will fail if the PATH contains '.' 
# (due to the security risk!). Before executing, set the PATH: 

#old path
#PATH='/usr/local/bin:/usr/bin:/bin:/usr/X12R6/bin:/opt/local/gmt/GMT4.3.1/bin'; export PATH

#new path
PATH='/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin'; export PATH


# Copy the latest data to the web server: 
find '/home/volcano/data/omi/output' -daystart -mtime -3 -type d ! -wholename '/home/volcano/data/omi/output' -execdir cp -r --preserve=timestamps \{\} -t /var/www/html/omi/data \;

# Delete OMI files older than 32 days from web server: #
find '/var/www/html/omi/data' -daystart -mtime +32 -type d ! -wholename '/var/www/html/omi/data' -execdir rm -r {} \;

# Copy the SO2 Emission Summary file to the web server data directory: 
cp '/home/volcano/programs/omi/logs/so2_summary.csv' '/var/www/html/omi/data'


# This script copies OMI SO2 images for the last 
# 5 days to the public FTP server. 
# Only images for Vanuatu are copied. 
# Also copies the summary file so2_summary.csv
# from the logs directory. 

DATESTR0=$(date --date="0 days ago" +%Y-%m-%d)
DATESTR1=$(date --date="1 days ago" +%Y-%m-%d)
DATESTR2=$(date --date="2 days ago" +%Y-%m-%d)
DATESTR3=$(date --date="3 days ago" +%Y-%m-%d)
DATESTR4=$(date --date="4 days ago" +%Y-%m-%d)

ftp -n ftp.gns.cri.nz <<End-Of-Session
user anonymous "omi-cronjob"
bin
prompt
cd "pub/incoming"
mkdir "omi"
cd "omi"
lcd "/home/volcano/data/omi/output/$DATESTR0"
mput *_Vanuatu*.png
lcd "/home/volcano/data/omi/output/$DATESTR1"
mput *_Vanuatu*.png
lcd "/home/volcano/data/omi/output/$DATESTR2"
mput *_Vanuatu*.png
lcd "/home/volcano/data/omi/output/$DATESTR3"
mput *_Vanuatu*.png
lcd "/home/volcano/data/omi/output/$DATESTR4"
mput *_Vanuatu*.png
lcd "/home/volcano/programs/omi/logs"
put "so2_summary.csv"
bye
End-Of-Session
